# Generated by Django 3.0 on 2023-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.TextField(verbose_name='Информация')),
            ],
        ),
    ]
